spring:
  datasource:
    url: jdbc:mysql://120.79.251.104:3306/my_blog_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080