spring:
  profiles:
    active: dev
server:
  port: 8888
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
    banner: false
  mapper-locations: classpath*:/mapper/*.xml
windy:
  security:
    imageCode:
      enable: false
    ignoreUrl: /test,/auth/form
#    /code/image
    injectClass: org.uppower.project.cashiermanagesystem.model.UserInfo
    accessTokenExpireIn: 7200