spring:
  profiles:
    active: dev
server:
  port: 443
  ssl:
    key-store: 2890437_tqktqk.cn.pfx
    key-store-password: aA1DT4iT
#    key-alias: tomcat1
#    key-store-type: PKCS12
#  max-http-header-size: 8999
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
    banner: false
  mapper-locations: classpath*:/mapper/*.xml
#  type-handlers-package: org.uppower.project.cashiermanagesystem.dao.typehandler
windy:
  security:
    imageCode:
      enable: false
    ignoreUrl: /test,/auth/form,/ci/out
#    /code/image
    injectClass: org.uppower.project.cashiermanagesystem.model.UserInfo
    accessTokenExpireIn: 7200
http:
  port: 80
wechat:
  appId: wx2c72530223447bcc
  secret: eb9d04821f27dd3f7af9994c5db5f5b5
  wxLoginUrl: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code