spring:
  #  devtools:
  #    restart:
  #      enabled: true
  #      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://47.106.217.214:3306/cashier?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: tuqikang
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379