spring:
  profiles:
    active: dev
server:
  port: 443
  ssl:
    key-store: 2890437_tqktqk.cn.pfx
    key-store-password: aA1DT4iT
#    key-alias: tomcat1
#    key-store-type: PKCS12
#  max-http-header-size: 8999
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
    banner: false
  mapper-locations: classpath*:/mapper/*.xml
windy:
  security:
    imageCode:
      enable: false
    ignoreUrl: /test,/auth/form,/ci/out
#    /code/image
    injectClass: org.uppower.project.cashiermanagesystem.model.UserInfo
    accessTokenExpireIn: 7200
http:
  port: 80